name: Generate compressed files of translations and push to the build branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/checkout@master

      - name: Compress
        run: |
          mkdir -p build
          find . -mindepth 1 -type d ! -path "./.git*" ! -path "./build" -print0 | xargs -0 -I % sh -c 'tar czf build/%.tar.gz %'
        shell: bash

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
